import { defineConfig } from 'vitepress'

// Grosso Link website (VitePress). Pages are generated by scripts/build_pages.py.
const base = process.env.SITE_BASE ?? '/'
const site = process.env.SITE_URL ?? 'https://grosso.link'

export default defineConfig({
  base,
  lang: 'en-US',
  title: 'Grosso Link',
  titleTemplate: ':title · Grosso Link',
  description: 'Grosso Link — Swiss Innovation. Custom ASIC partner for high-performance sensor and mixed-signal ICs.',
  cleanUrls: true,
  lastUpdated: false,
  // 原站是浅色主题：只保留浅色，不显示明暗切换
  appearance: false,
  sitemap: { hostname: site + base },
  head: [
    ['link', { rel: 'icon', type: 'image/png', href: `${base}img/logo.png` }],
    ['meta', { name: 'theme-color', content: '#ffffff' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300&display=swap' }],
  ],
  transformPageData(pageData) {
    const url = site + base + pageData.relativePath.replace(/((^|\/)index)?\.md$/, '$2')
    pageData.frontmatter.head ??= []
    pageData.frontmatter.head.push(
      ['link', { rel: 'canonical', href: url }],
      ['meta', { property: 'og:site_name', content: 'Grosso Link' }],
      ['meta', { property: 'og:title', content: pageData.frontmatter.title || pageData.title || 'Grosso Link' }],
      ['meta', { property: 'og:description', content: pageData.frontmatter.description || '' }],
      ['meta', { property: 'og:url', content: url }],
      ['meta', { property: 'og:image', content: site + base + 'img/logo.png' }],
    )
  },
  vue: { template: { transformAssetUrls: false } },
  themeConfig: {
    logo: { src: '/img/logo-t.png', alt: 'Grosso Link — Swiss Innovation' },
    siteTitle: false,
    nav: [
      { text: 'Technology', link: '/technology' },
      { text: 'Custom ASIC', link: '/custom-asic' },
      { text: 'About us', link: '/about-us' },
      { text: 'Contact', link: '/contact' },
    ],
    outline: false,
    docFooter: { prev: false, next: false },
    footer: {
      message: '<span class="gl-swiss" aria-hidden="true"></span> Designed in Switzerland · St. Jakobstrasse 58, 6330 Cham · <a href="mailto:info@grosso.link">info@grosso.link</a>',
      copyright: `© ${new Date().getFullYear()} Grosso Link GmbH — Swiss Innovation`,
    },
  },
})
